apiVersion: v1
kind: ConfigMap
metadata:
  name: grade-submission-api-config
  namespace: grade-submission
data:
  MONGODB_HOST: "mongodb"  ## mongodb service name used for internal DNS resolution
  MONGODB_PORT: "27017"