apiVersion: v1
kind: Service
metadata:
  name: grade-submission-portal  ## Uniquely identifies the service
  namespace: grade-submission
spec:
  type: NodePort  ## Exposes the service on each Node's IP at a static port
  selector:
    app.kubernetes.io/instance: grade-submission-portal  ## Selects pods with this label
  ports:
  - port: 5001 ## Port on which the service is exposed, internal
    targetPort: 5001  ## Port on the pod to which traffic is directed
    nodePort: 32000  ## Port on each node to expose the service externally (browser access on localhost:32000), range 30000-32767
