apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    app.kubernetes.io/instance: mongodb ## Selects pods with this label
  ports:
  - port: 27017
    targetPort: 27017
