apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque ## assumes base64 encoding
data:  ## the data field expects base64 encoded values
  MONGODB_USER: "YWRtaW4="
  MONGODB_PASSWORD: "cGFzc3dvcmQxMjM0"
